import { Clip, Project, SocialAccount } from "./types";

export const mockSocialAccounts: SocialAccount[] = [
  { platform: "tiktok", connected: true, username: "@clipinc_demo" },
  { platform: "youtube", connected: true, username: "ClipInc Demo" },
  { platform: "instagram", connected: false },
  { platform: "twitter", connected: false },
];

const baseCaptions = [
  { id: "c1", text: "The thing about building a startup is...", startTime: 0, endTime: 3 },
  { id: "c2", text: "you have to be comfortable with chaos.", startTime: 3, endTime: 6 },
  { id: "c3", text: "Every single day is different.", startTime: 6, endTime: 9 },
  { id: "c4", text: "And that's what makes it exciting.", startTime: 9, endTime: 12 },
];

export const mockClips: Clip[] = [
  {
    id: "clip-1",
    projectId: "proj-1",
    title: "The Startup Chaos",
    description: "Key insight about startup life and embracing uncertainty",
    startTime: 124,
    endTime: 156,
    duration: 32,
    aspectRatio: "9:16",
    status: "ready",
    score: 95,
    captions: baseCaptions,
    thumbnail: "",
    publishedTo: [],
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "clip-2",
    projectId: "proj-1",
    title: "Why We Pivoted",
    description: "The story behind our biggest pivot and what we learned",
    startTime: 340,
    endTime: 398,
    duration: 58,
    aspectRatio: "9:16",
    status: "exported",
    score: 91,
    captions: baseCaptions,
    thumbnail: "",
    publishedTo: ["tiktok"],
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "clip-3",
    projectId: "proj-1",
    title: "Fundraising Tips",
    description: "Three unconventional tips for first-time founders raising capital",
    startTime: 780,
    endTime: 825,
    duration: 45,
    aspectRatio: "1:1",
    status: "published",
    score: 88,
    captions: baseCaptions,
    thumbnail: "",
    publishedTo: ["youtube", "tiktok"],
    createdAt: "2026-06-14T18:00:00Z",
  },
  {
    id: "clip-4",
    projectId: "proj-2",
    title: "AI in Healthcare",
    description: "How AI is transforming patient diagnostics",
    startTime: 60,
    endTime: 105,
    duration: 45,
    aspectRatio: "16:9",
    status: "ready",
    score: 85,
    captions: baseCaptions,
    thumbnail: "",
    publishedTo: [],
    createdAt: "2026-06-13T14:00:00Z",
  },
  {
    id: "clip-5",
    projectId: "proj-2",
    title: "The Future of Remote Work",
    description: "Bold predictions about how we'll work in 2030",
    startTime: 512,
    endTime: 548,
    duration: 36,
    aspectRatio: "9:16",
    status: "ready",
    score: 82,
    captions: baseCaptions,
    thumbnail: "",
    publishedTo: [],
    createdAt: "2026-06-13T14:00:00Z",
  },
  {
    id: "clip-6",
    projectId: "proj-3",
    title: "Content Creation Secrets",
    description: "The algorithm hack nobody talks about",
    startTime: 200,
    endTime: 230,
    duration: 30,
    aspectRatio: "9:16",
    status: "published",
    score: 79,
    captions: baseCaptions,
    thumbnail: "",
    publishedTo: ["instagram", "tiktok", "youtube"],
    createdAt: "2026-06-12T09:00:00Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    title: "The Startup Diaries - Episode 47",
    sourceUrl: "https://youtube.com/watch?v=example1",
    duration: 3720,
    processingStep: "complete",
    processingProgress: 100,
    clips: mockClips.filter((c) => c.projectId === "proj-1"),
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "proj-2",
    title: "Tech Talks Weekly - AI Special",
    fileName: "tech-talks-ai-special.mp4",
    duration: 2400,
    processingStep: "complete",
    processingProgress: 100,
    clips: mockClips.filter((c) => c.projectId === "proj-2"),
    createdAt: "2026-06-13T14:00:00Z",
  },
  {
    id: "proj-3",
    title: "Creator Economy Podcast",
    sourceUrl: "https://youtube.com/watch?v=example3",
    duration: 1800,
    processingStep: "complete",
    processingProgress: 100,
    clips: mockClips.filter((c) => c.projectId === "proj-3"),
    createdAt: "2026-06-12T09:00:00Z",
  },
];
